version: '2'
services:
  nodejs-helloworld:
    volumes:
        - ./app_dir:/app
    working_dir: "/app"
    # ports:
    #     - "80:3000"
    image: node
    command: 'npm start'
    labels:
      # - "traefik.backend=foo"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.weight=10"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nodejs-helloworld.louislabs.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.priority=10"
      - "traefik.frontend.entryPoints=http"
      - "traefik.docker.network=proxy"
    container_name: nodejs-helloworld
